### ISSUE TITLE
ns1_record answer meta field region not applied

### ISSUE THREAD

**Issue by h110hawk** [ns1-terraform/terraform-provider-ns1#20] opened 2018-02-09 01:43 UTC
### Terraform Version
Terraform v0.11.2
+ provider.ns1 v1.0.0

### Affected Resource(s)
ns1_record

### Terraform Configuration Files
```
resource "ns1_record" "cname___example" {
     zone = "${ns1_zone.test-domain_net.zone}"
     domain = "example.${ns1_zone.test-domain_net.zone}"
     type = "CNAME"
     ttl = 10800

     answers = {
          answer = "a.example.com."
          meta = {
               region = "ExampleRegionA"
          }
     }

     answers = {
          answer = "b.example.com."
          meta = {
               region = "ExampleRegionB"
          }
     }

     regions = [
          {
               name = "ExampleRegionA"
               meta = {
                    country = "AS"
                    country = "AU"
               }
          },
          {
               name = "ExampleRegionB"
               meta = {
                    country = "US"
                    country = "CA"
                    us_state = "AL"
                    us_state = "NY"
               }
          }
     ]
}
```
### terraform output
```ns1_record.cname___example: Creating...
  answers.#:               "" => "2"
  answers.0.answer:        "" => "a.example.com."
  answers.0.meta.%:        "" => "1"
  answers.0.meta.region:   "" => "ExampleRegionA"
  answers.1.answer:        "" => "b.example.com."
  answers.1.meta.%:        "" => "1"
  answers.1.meta.region:   "" => "ExampleRegionB"
  domain:                  "" => "example.test-domain.net"
  regions.#:               "" => "2"
  regions.0.meta.%:        "" => "1"
  regions.0.meta.country:  "" => "AU"
  regions.0.name:          "" => "ExampleRegionA"
  regions.1.meta.%:        "" => "2"
  regions.1.meta.country:  "" => "CA"
  regions.1.meta.us_state: "" => "NY"
  regions.1.name:          "" => "ExampleRegionB"
  ttl:                     "" => "10800"
  type:                    "" => "CNAME"
  use_client_subnet:       "" => "true"
```
### NS1 output
```
{
  "domain": "example.test-domain.net",
  "zone": "test-domain.net",
  "use_client_subnet": true,
  "answers": [
    {
      "answer": [
        "a.example.com."
      ],
      "meta": {},
      "id": "5"
    },
    {
      "answer": [
        "b.example.com."
      ],
      "meta": {},
      "id": "5"
    }
  ],
  "id": "5",
  "regions": {
    "ExampleRegionA": {
      "meta": {
        "country": [
          "AU"
        ]
      }
    },
    "ExampleRegionB": {
      "meta": {
        "country": [
          "CA"
        ]
      }
    }
  },
  "meta": {},
  "link": null,
  "filters": [],
  "ttl": 10800,
  "tier": 1,
  "type": "CNAME",
  "networks": [
    0
  ]
}
```
### Expected Behavior
What should have happened?
Answers should have "region" metadata

### Actual Behavior
What actually happened?
They don't.

**Comment by alistanis** [comment] 2018-02-09 16:12
Hi @h110hawk, admittedly the documentation for this could be better. I've at least updated the readme on my current working branch and hopefully I'll have something out for #19 soon - but for this particular problem - meta doesn't have a region field, the answer does, so change the location of the region from meta to the answers and you should be fine for that. Also, answers is a list, so instead of this:

```
answers = {
          answer = "a.example.com."
          meta = {
               region = "ExampleRegionA"
          }
     }

     answers = {
          answer = "b.example.com."
          meta = {
               region = "ExampleRegionB"
          }
     }
```

you could have this:

```
answers = [
     {
          answer = "a.example.com."
          region = "ExampleRegionA"
     },
     {
          answer = "b.example.com."
          region = "ExampleRegionB"
      }    
     ]
```

Also, I noticed that in the regions array, you've defined country and us_state multiple times in the meta fields for those regions - the meta field is a map, so only the last one read would ever be applied. Instead, use comma separated lists:

```
regions = [
          {
               name = "ExampleRegionA"
               meta = {
                    country = "AS,AU"
               }
          }
]
```

Now, I believe that #19 would still cause a problem here when trying to apply the countries and states, but that should put you on the right track as far as the template goes. I will hopefully have something out for #19 soon.

**Comment by h110hawk** [comment] 2018-02-09 16:58
@alistanis Thank you for the rapid response and  comprehensive critique! I've updated my import script to generate something that I believe to be a much closer approximation to correct. New errors ahoy:
```
resource "ns1_record" "cname___example" {
     zone = "${ns1_zone.test-domain_net.zone}"
     domain = "example.${ns1_zone.test-domain_net.zone}"
     type = "CNAME"
     ttl = 10800

     answers = [
          {
               answer = "a.example.com."
               region = "ExampleRegionA"
          },
          {
               answer = "b.example.com."
               region = "ExampleRegionB"
          }
     ]

     regions = [
          {
               name = "ExampleRegionA"
               meta = {
                    country= "AS,AU,CC,CK,CX,FJ,FM,GU,HM,KI,MH,MP,NC,NF,NR,NU,NZ,PF,PG,PN,PW,SB,TK,TO,TV,U9,VU,WF,WS"
               }
          },
          {
               name = "ExampleRegionB"
               meta = {
                    country= "A3,PM"
                    us_state= "AK,AP,AR,AZ,CA,CO,HI,ID,KS,MT,ND,NE,NV,OR,SD,U1,UM,UT,WA,WY"
                    ca_province= "AB,BC,NT,SK,U2,YT"
               }
          }
     ]
}
```

`terraform plan` works, `terraform apply` yields:

```ns1_record.cname___example: Creating...
  answers.#:                  "" => "2"
  answers.0.answer:           "" => "a.example.com."
  answers.0.region:           "" => "ExampleRegionA"
  answers.1.answer:           "" => "b.example.com."
  answers.1.region:           "" => "ExampleRegionB"
  domain:                     "" => "example.test-domain.net"
  regions.#:                  "" => "2"
  regions.0.meta.%:           "" => "1"
  regions.0.meta.country:     "" => "AS,AU,CC,CK,CX,FJ,FM,GU,HM,KI,MH,MP,NC,NF,NR,NU,NZ,PF,PG,PN,PW,SB,TK,TO,TV,U9,VU,WF,WS"
  regions.0.name:             "" => "ExampleRegionA"
  regions.1.meta.%:           "" => "3"
  regions.1.meta.ca_province: "" => "AB,BC,NT,SK,U2,YT"
  regions.1.meta.country:     "" => "A3,PM"
  regions.1.meta.us_state:    "" => "AK,AP,AR,AZ,CA,CO,HI,ID,KS,MT,ND,NE,NV,OR,SD,U1,UM,UT,WA,WY"
  regions.1.name:             "" => "ExampleRegionB"
  ttl:                        "" => "10800"
  type:                       "" => "CNAME"
  use_client_subnet:          "" => "true"
  zone:                       "" => "ttd-test-domain.net"

Error: Error applying plan:

1 error(s) occurred:

* ns1_record.cname___example: 1 error(s) occurred:

* ns1_record.cname___example: unexpected EOF

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

**Comment by alistanis** [comment] 2018-02-09 17:14
@h110hawk sure thing, that's essentially #19 right there. Thanks for posting your output, it's pretty much what I expected but always nice to have confirmation. I'm working on #19 as we speak, so I will hopefully have something out soon.

**Comment by ThiagoYU** [comment] 2021-09-30 17:54
Hello @h110hawk, can you confirm this is solved?

**Comment by eravin-ns1** [comment] 2022-12-06 00:35
Looks like a duplicate of #19 
We also fixed another regions bug in v.1.13.1.
If you still see any problems, please open a new issue.

**Closed by eravin-ns1** 2022-12-06 00:35 UTC
